###
GET http://localhost:3000/api/public_products

###
GET http://localhost:3000/api/public_products/1

###
GET http://localhost:3000/api/public_products/cat/moda

###

GET http://localhost:3000/api/products

###

GET http://localhost:3000/api/products/v2

###

GET http://localhost:3000/api/products/2

###

GET http://localhost:3000/api/products/2/v2

###

GET http://localhost:3000/api/products/cat/moda

###

GET http://localhost:3000/api/clients

###

GET http://localhost:3000/api/products

###

GET http://localhost:3000/api/products?page=1&limit=5

###
// user logado y A de admin
GET http://localhost:3000/api/clients/user

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "cantimplora azul",
  "description": "cantimplora de montaña",
  "price": 10,
  "category": "aventura"
}

###

POST http://localhost:3000/api/clients

###

PUT http://localhost:3000/api/products/5
Content-Type: application/json

{
  "name": "cantimplora azul",
  "description": "cantimplora de montaña",
  "price": 20,
  "category": "aventura"
}

###

DELETE http://localhost:3000/api/products/5

###